name: Show GP4 Template

on:
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-22.04

    steps:
      - name: Show template.gp4
        run: |
          docker run --rm --user root \
            openorbisofficial/toolchain:latest \
            bash -c 'cat /lib/OpenOrbisSDK/bin/data/template.gp4'
